### ISSUE TITLE
Compiler warning of no previous prototype for `signal_wait_until`

### ISSUE THREAD

**Issue by wrrobin** [Sandia-OpenSHMEM/SOS#1039]
The following warning appears during SOS build

synchronization_c.c:1253:1: warning: no previous prototype for ‘shmem_signal_wait_until’ [-Wmissing-prototypes]
 shmem_signal_wait_until(uint64_t *sig_addr, int cmp, uint64_t cmp_value)

**Comment by davidozog** [comment]
@kholland-intel and I saw this same warning, and I think it's due to not doing a full "clean" before building from the binding generations of a previous build.

Are you seeing this from a clean build directory?  (I think "make distclean" should resolve this, but I only tried removing everything then reconfiguring).

**Comment by wrrobin** [comment]
`make clean` resolves the issue.
