### ISSUE TITLE
No path to peer error

### ISSUE THREAD

**Issue by WrongWizzli** [Sandia-OpenSHMEM/SOS#1090]
I am trying to build OpenSHMEM package on Linux Mint 20.3 with the following commands:
```
./autogen.sh
./configure --enable-pmi-simple
make
make check
```
However on `make check` step I am getting 66 tests failed with the same reason `No path to peer`. The full example of single test log:
```
FAIL: mt_membar
===============

Starting multi-threaded test on 1 PEs, 2 threads/PE
[0000] ERROR: transport_none.h:214: shmem_transport_atomic
[0000]        No path to peer
Sandia OpenSHMEM exited in error
[0000] WARN:  init.c:137: shmem_internal_shutdown_atexit
[0000]        shutting down without a call to shmem_finalize
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
[0000] ERROR: transport_none.h:214: shmem_transport_atomic
[0000]        No path to peer
Sandia OpenSHMEM exited in error
[0000] WARN:  init.c:137: shmem_internal_shutdown_atexit
[0000]        shutting down without a call to shmem_finalize
Starting multi-threaded test on 1 PEs, 2 threads/PE
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[36188,1],0]
  Exit code:    1
--------------------------------------------------------------------------
FAIL mt_membar (exit status: 1)
```
Could you please suggest what might be the reason for such failure?

**Comment by WrongWizzli** [comment]
While running `make` I also get warning:
`WARNING: No transport found, resulting library will be unable to exchange messages`

**Comment by davidozog** [comment]
Currently to run with multiple processes you need to enable a shared memory transport.  Your options are XPMEM (`--with-xpmem`), CMA (`--with-cma`), or OFI with the sockets provider (`--with-ofi`); however, these can be tricky to build/install sometimes and performance widely varies...  May I ask what is your use-case?

If your know how to checkout and build a different git branch, you could also try our experimental mmap transport here: https://github.com/davidozog/sandia-shmem/tree/wip/mmap_xpmem_heap
and passing `--enable-mmap`.
Let me know if you would like help trying that.

**Comment by ivan-pi** [comment]
Just encountered the same issue trying to run SOS locally. 

I managed to get a working installation with:
```
$ git clone https://github.com/davidozog/sandia-shmem.git SOS-mmap
$ cd SOS-mmap
$ git checkout wip/mmap_xpmem_heap 
$ git submodule update --init
$ ./autogen.sh
$ CC=mpiicx CXX=mpiicpx FC=mpiifort ./configure --prefix=/home/ivan/.local/SOS --enable-mmap --enable-error-checking --enable-pmi-simple
$ make
$ make check
```
and all tests passing successfully. For running on a single node (develop code locally on a workstation) is there any reason to prefer XPMEM, CMA, Sockets or MMAP?

**Comment by davidozog** [comment]
@ivan-pi - I'm so glad this works for you and thank you for the notes!

I was also enjoying `--enable-mmap` on Ubuntu 24.04 just when I saw your question.

> For running on a single node (develop code locally on a workstation) is there any reason to prefer XPMEM, CMA, Sockets or MMAP?

We are investigating now;  XPMEM is probably best performance-wise but difficult to install except in the most basic linux configurations and requires sudo.  The performance of mmap competes well with XPMEM, except possibly in rare circumstances but mmap is not yet merged to `main`.  CMA unfortunately has major performance problems we have not yet identified; so unfortunately I cannot recommend it except as a last resort.  OFI/libfabric is usually a better way to go.

We are also working to enable the libfabric `shm` provider as well, but the sockets provider shouldn't be used for performance unless it's necessary.

`mmap` transport seems fast and portable; but we are still working to merge for pedantic reasons @markbrown314

Side note: in your configuration I might recommend instead using pmi-MPI:

```
$ CC=mpiicx CXX=mpiicpx FC=mpiifort ./configure --prefix=/home/ivan/.local/SOS --enable-mmap --enable-error-checking --enable-pmi-mpi
```
Otherwise you might confuse the software stack because I am suspicious that `pmi-simple` is very portable alongside MPI like this.  This may also fix your Fortran issue.  If either or neither case, please let me know if this is an important use-case.

If you are only on a single node  (i.e., no network) and the performance of `shmem_atomic` matters (always, right?) then I might recommend adding `--enable-shr-atomics`.  Enjoy!

**Comment by ivan-pi** [comment]
Thanks for the explanation. After using `--enable-pmi-mpi` also `mpirun` works. 👍🏻 

This might be just a false feeling, but there is slight latency when launching compared with `pmi-simple`. Right now I was just in need to get something running so I can learn more about OpenSHMEM programming. Looking forward to try it also on [larger machines](https://doku.lrz.de/hardware-of-supermuc-ng-phase-2-222891050.html).

**Comment by davidozog** [comment]
Sounds good!

Also, you do not need MPI to build SOS, you might have faster "make check" for development if you built like this:

```
$ CC=icx CXX=icpx FC=ifort ./configure --prefix=/home/ivan/.local/SOS --enable-mmap --enable-error-checking --enable-pmi-simple --enable-shr-atomics
```

In that case there's less concern about possible PMI runtime weirdness, if I'm not mistaken.

However, the MPI configuration with `--enable-pmi-mpi` is likely preferable on a system like SuperMUC@LRZ.
