### ISSUE TITLE
OSHRUN Search List

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#113]
The `oshrun` search list should be generated at configure time based on the process manager selection made by the user (e.g. internal PMI, Portals PMI, or SLURM).

**Comment by richardnorth3** [comment]
This issue gets closed by #420 right?

**Comment by jdinan** [comment]
Nope.

**Comment by jdinan** [comment]
@angelali4096

**Comment by angelali4096** [comment]
I believe that having a search list of launchers based on PMI selection is not necessary. 
At the moment, our search list consist of "yod mpirun mpiexec(equivalent to mpirun) srun" and we have 3 possible configurations for using PMI: PMI1/pmi-simple, PMI2, and PMIx. (For the purposes of this explanation, I will not discuss yod because I'm unfamiliar with how it works.)

Case 1: PMI1/pmi-simple
mpirun - whether the OpenMPI or MPICH implementation, supports PMI1
srun - SLURM supports the PMIx library, which is backwards compatible with PMI1 and PMI2
The search list for PMI1/pmi-simple will be "mpirun/mpiexec srun".

Case 2: PMI2
Same explanation as with Case 1.

Case 3: PMIx
mpirun - Currently OpenMPI supports PMIx, MPICH does not. At the moment, we cannot differentiate between the two implementations so this launcher is still applicable.
srun - SLURM supports the PMIx library
The search list for PMIx will be "mpirun/mpiexec srun".

So the search list for any PMI configuration will be identical.

**Comment by jdinan** [comment]
Thanks, let's close as wontfix
