### ISSUE TITLE
Tests as separate sub-module

### ISSUE THREAD

**Issue by naveen-rn** [Sandia-OpenSHMEM/SOS#147]
Unit test cases in this repository looks very comprehensive and also tests OpenSHMEM-1.3 features. If it is possible, can we make this as separate repository and add as a submodule in this repo. This would allow to use these tests in other SHMEM implementations.

**Comment by jdinan** [comment]
I think we're open to this, but we don't have the developer resources to tackle it at the moment.  I'm not sure that a git submodule is the best long-term approach, since we're using automake to run tests and others would presumably want to use a different harness.

Do you have any suggestions in terms of a test harness or an example that you think was done well?  It looks like the test harness used by [openshmem-org/tests-cray](https://github.com/openshmem-org/tests-cray) are roughly equivalent to what automake does for us currently.  I've also invested a fair amount of effort into improving the [openshmem-org/tests-uh](https://github.com/openshmem-org/tests-uh) harness; that could be another option.

If it's useful enough in your work, I'd be happy to talk about working together on this.

**Comment by sayantansur** [comment]
+1 to ONE community maintained testing harness and tests.

**Comment by jdinan** [comment]
This issue is now closed -- https://github.com/openshmem-org/tests-sos :tada:
