### ISSUE TITLE
mr_reg heap failed with GNI provider

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#524]
I get the following error with SOS and libfabric master on Cori@NERSC:

```
ozog@nid00523: ~/Repos/SOS/test/unit $ ./hello
[0000] WARN:  ../../../src/transport_ofi.c:546: allocate_recv_cntr_mr
[0000]        mr_reg heap failed
[0000] ERROR: ../../../src/init.c:238: shmem_internal_init
[0000]        Transport init failed (-22)
```

Here is my configure line:
```
../configure --disable-mr-scalable --with-xpmem=/opt/cray/xpmem/default --enable-completion-polling --enable-threads --with-pmi=/opt/cray/pe/pmi/default --prefix=<my_prefix> --with-ofi=<my_libfabric> --enable-debug CFLAGS=-O0
```

A similar error was reported by @yburette on Edison:
```
libfabric:gni:mr:__gnix_generic_register():404<info> [15403:1] could not allocate nic to do mr_reg, ret=-22
libfabric:gni:mr:__mr_cache_create_registration():1451<info> [15403:1] failed to register memory with callback
fi_mr_reg(): common/shared.c:395, ret=-12 (Cannot allocate memory)
```

**Comment by davidozog** [comment]
I used `git bisect` (for the first time - it's a fantastic tool) to find the first libfabric commit where things went wrong for SOS.  It's here:
https://github.com/ofiwg/libfabric/commit/4a0e5c5ac327d3190262fb0dc15f62873ae328ce

**Comment by davidozog** [comment]
On libfabric master, we're falling into this conditional:
https://github.com/ofiwg/libfabric/blob/master/prov/gni/src/gnix_mr.c#L266

**Comment by jdinan** [comment]
@jswaro Might be able to help.  Looks like that commit added support for ```MR_SCALABLE```.  Have you tried using that (remove --disable-mr-scalable) instead of ```MR_BASIC```?

**Comment by jswaro** [comment]
That conditional suggests that you are using basic registration (FI_MR_PROV_KEY in 1.5 terms), and you have a provided a non-zero key. In that specific case, the provider assumes this is an error on the part of the application and returns FI_EINVAL.

**Comment by jdinan** [comment]
Yes, we are supplying nonzero requested key values with MR_BASIC (intentionally, since the same code handles both MR_BASIC and MR_SCALABLE).  IIUC, the requested key should be ignored by the provider rather than causing an error (which is what we've been relying on).  Although, I can't now find the relevant text in OFI to back this up -- maybe @shefty can clarify.

**Comment by shefty** [comment]
The key is listed as optional, so having the provider ignore the value when not used seems reasonable.  I don't see any specific text on the key when not used -- and that includes that there's no requirement that it be 0.

As a proposal, I vote for ignoring it, but allowing a provider to display a warning message if it is non-zero, indicating that it is ignored.

**Comment by jswaro** [comment]
I'm fine with ignoring it. I may opt for the warning because there should be some indication that the key provided will not be used,

**Comment by hppritcha** [comment]
see https://github.com/Sandia-OpenSHMEM/SOS/pull/525

**Comment by jdinan** [comment]
Isn't zero also a valid key?  I don't see how a provider can conclude the usage model is safe since the application can request zero and then incorrectly assume a zero key later on.  If you want to warn/error, then we really should introduce an invalid key constant and require that it be passed with MR_BASIC.

**Comment by jdinan** [comment]
Bueller?

**Comment by shefty** [comment]
0 is a valid key.  I was suggesting that in the BASIC case, the provider can display a message if the key is non-zero to indicate that it will be ignored.  I'm also fine not having the message.  But the provider should just ignore the value, rather than assume anything about it.  We can't introduce an 'invalid key' value at this point, because an app may already be using whatever value we select, so picking 0 is just as good as any other value.

**Comment by jswaro** [comment]
This should already be fixed in the GNI provider.

**Comment by jdinan** [comment]
Sounds like we can close this issue.  Thanks for the help!
