### ISSUE TITLE
Update wiki to include PSM2 performance considerations

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#646]
Achieving the best performance for SOS applications on PSM2 with multiple threads/contexts/OFI STXs can be a relatively complicated endeavor.  The wiki should describe these performance issues and how to change relevant configurations such as manual progress, PSM2_PROG_INTERVAL, setting the SHMEM_OFI_STX_* environment variables, binding processes to cores, etc.

**Comment by jdinan** [comment]
Note: Indicate that PSM2 users should use libfabric 1.6 or later.

**Comment by davidozog** [comment]
Note:  we prefer libfabric v1.6 on PSM2 for v1.4.1rc1

**Comment by jdinan** [comment]
Document `FI_PSM2_LAZY_CONN` (or adopt the same solution? 🤢 ) -- https://bitbucket.org/berkeleylab/gasnet/commits/58d396dfcffbd46562cfb555bd633cb1c8229043

**Comment by davidozog** [comment]
FYI: I've written a rough draft of a "Performance Tuning" page for the SOS wiki on my fork:
https://github.com/davidozog/sandia-shmem/wiki/Performance-Tuning

With regards to `FI_PSM2_LAZY_CONN`, I'm not sure.  Do you think we should do this in SOS, @epaulson10?  Under what conditions does the default "non-lazy" conn degrade performance?  Thanks!

**Comment by davidozog** [comment]
For now, I've documented `FI_PSM2_LAZY_CONN` in the new [Performance Tuning wiki page](https://github.com/Sandia-OpenSHMEM/SOS/wiki/Performance-Tuning).  

I've also created a separate issue for lazy connections (#667) in case we want to make this the default option in SOS.

**Comment by epaulson10** [comment]
Hi Dave, sorry it has taken a while to get back to you. I have left Intel so I'm not checking my libfabric notifications very much. The reason why we did the lazy connection code is because teardown was taking forever. This is due to the fact that GASNet has three endpoints, which ended up causing pairwise connections being formed in psm2-land between them (in libfabric 1.6), even though they weren't actually all talking to each other. Tearing down all these connections took way too long, which is why I started setting the lazy connection variable. As far as I can tell, setting that variable doesn't affect the actual performance of transferring data, but you should take that with a grain of salt.

**Comment by davidozog** [comment]
Thanks @epaulson10!  That lazy connection issue migrated to #667 and is now closed.

I'll close[ *this* ](https://github.com/Sandia-OpenSHMEM/SOS/issues/646) PSM2 wiki issue with the caveat that all SOS performance-related updates should now go into the [Performance Tuning](https://github.com/Sandia-OpenSHMEM/SOS/wiki/Performance-Tuning) page.
