### ISSUE TITLE
OFI: Rand is not thread safe

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#677]
In `transport_ofi.h` use `rand_r` instead of `rand` to avoid problems with threading (e.g. if an application thread is also using `rand`).

**Comment by davidozog** [comment]
Making this change seems surprisingly non-trivial.  We need a thread-local `unsigned int` seed for `rand_r`, and we can't safely use `shmem_internal_tid` type directly because it's either `pid_t` or `uint64_t`, right?  Not sure I feel ok about a thread-local `time()` seed either.   Even getting a portable thread-local variable with c99 seems non-trivial (see [here](https://stackoverflow.com/questions/18298280/how-to-declare-a-variable-as-thread-local-portably)).  We could use `pthread_get/set_specific` I suppose...  Any thoughts?  Maybe I'm missing something.

**Comment by jdinan** [comment]
Is this for the STX allocator?  If so, there's a mutex for the STX allocator / context creation -- can we create a shared seed variable that's used by all threads in the PE and protected by that mutex?  Maybe initialize to the PE id?
